### ISSUE TITLE
fill_initial_team fails to get history data

### ISSUE THREAD

**Issue by Tdarnell** [alan-turing-institute/AIrsenal#244]
fill_initial_team is returning with index error, as there is no history data for pid 35 in week 1. This player did not have week 1 fixtures.

A check needs to be added for no player history data, in which case their price needs determining another way. I have added a hacky check for pid 35 and set it to the 2018/2019 value for generating my initial squad.

```
Data not available for player 35 week 1
Traceback (most recent call last):
  File "/home/tom/.local/bin/airsenal_setup_initial_db", line 33, in <module>
    sys.exit(load_entry_point('airsenal', 'console_scripts', 'airsenal_setup_initial_db')())
  File "/mnt/d/PycharmProjects/AIrsenal/airsenal/scripts/fill_db_init.py", line 27, in main
    fill_initial_team(session)
  File "/mnt/d/PycharmProjects/AIrsenal/airsenal/framework/transaction_utils.py", line 47, in fill_initial_team
    price = gw1_data[0]["value"]
IndexError: list index out of range
```

Data from FPL API:

```
,"history":[],"history_past":[{"season_name":"2019/20","element_code":98770,"start_cost":45,"end_cost":43,"total_points":15,"minutes":537,"goals_scored":0,"assists":0,"clean_sheets":1,"goals_conceded":12,"own_goals":0,"penalties_saved":0,"penalties_missed":0,"yellow_cards":0,"red_cards":0,"saves":15,"bonus":0,"bps":90,"influence":"101.2","creativity":"0.0","threat":"0.0","ict_index":"10.2"}]}
```

**Comment by jack89roberts** [comment]
Hi @Tdarnell , have you updated the database by running `airsenal_update_db`? This should give you prices for all the players (including those without a week 1 fixture). If new players have been added since you created the database (quite likely at the moment) it's safer to delete and recreate the database instead:
```shell
rm /tmp/data.db
airsenal_setup_initial_db
airsenal_update_db --noattr
```

If you still get the error above after doing that then this is a new bug we'll need to investigate.

**Comment by jack89roberts** [comment]
@Hughesy also had this issue (originally #245) and the above didn't seem to fix it.

Did either of you have Man Utd, Man City, Aston Villa or Burnley players (who didn't have a fixture) in your initial squads for gameweek 1?

**Comment by Hughesy** [comment]
I can confirm only players in my initial squad had a fixture during game week 1.

**Comment by jack89roberts** [comment]
@carlmacdiarmada also has this issue (originally #246):
> Hi,
> 
> I have an error when running the initial db setup
> 
> ```
> Data not available for player 35 week 1
> Traceback (most recent call last):
>   File "c:\users\carl\.conda\envs\airsenalenv\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\users\carl\.conda\envs\airsenalenv\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\Carl\.conda\envs\airsenalenv\Scripts\airsenal_setup_initial_db.exe\__main__.py", line 7, in <module>
>   File "c:\users\carl\.conda\envs\airsenalenv\lib\site-packages\airsenal\scripts\fill_db_init.py", line 27, in main
>     fill_initial_team(session)
>   File "c:\users\carl\.conda\envs\airsenalenv\lib\site-packages\airsenal\framework\transaction_utils.py", line 47, in fill_initial_team
>     price = gw1_data[0]["value"]
> IndexError: list index out of range
> ```
> 
> team : https://fantasy.premierleague.com/entry/2007170/event/1
> 
> I have tried the fix outline [here](https://github.com/alan-turing-institute/AIrsenal/issues/244#issuecomment-692608772) but unfortunately no joy

In this case, Walker is in the squad, who did is one of the players without a fixture in GW1.

I don't have the problem running on my laptop, so will need to have a think about what could cause this. If you could all let me know your team IDs I can then hopefully recreate the bug.

**Comment by Hughesy** [comment]
My team ID is 1246844

**Comment by Tdarnell** [comment]
My team ID is 2833283, I have encountered this error running it for a friends team too ID: 4305666

```rm /tmp/data.db
airsenal_setup_initial_db
airsenal_update_db --noattr```

This fails as the setup_initial_db does not pull the initial team - it faults and stops after the first history=[]

**Comment by jack89roberts** [comment]
Ah right yes as you suggested in the original comment it looks like this is a weird edge case in the API that we haven't come up against before, namely what happens when there are teams with no fixture in gameweek 1. Hopefully it shouldn't be too difficult to fix, I'll try to look this evening.

**Comment by jack89roberts** [comment]
Hi all here, I believe I've fixed the problem, it's a matter of finding the starting price for players in a different place in the API for those that had a blank gameweek 1.

The fix will be merged to master at some point, but for now it's on our develop branch. To install it you'll need to pull the latest status of the repo, checkout the develop branch, and reinstall AIrsenal by doing the following from the parent AIrsenal directory:
```shell
rm /tmp/data.db
git checkout develop
git pull
pip install --upgrade --force-reinstall .
```

After that I hope you should be able to run AIrsenal normally again as described in the readme (`airsenal_setup_initial_db`, then `airsenal_update_db`, then `airsenal_run_prediction`, and finally `airsenal_run_optimizatinon`. Or alternatively just `airsenal_run_pipeline` which does all of those steps for you.)

**Comment by maxquinn** [comment]
@jack89roberts just tried on my previously failing team. Works perfectly! Thanks for the fix

**Comment by Hughesy** [comment]
I have tried twice and still can't seem to get it working. I still get this error message
<img width="1152" alt="Screenshot 2020-09-16 at 00 20 09" src="https://user-images.githubusercontent.com/2457878/93274536-8244ae80-f7b2-11ea-9d62-aacdd7aee6bb.png">

**Comment by jack89roberts** [comment]
@Hughesy Ah right, looks like you have a different problem. I'll reopen the issue you made yesterday.

**Comment by carlmacdiarmada** [comment]
thanks @jack89roberts ran perfectly on my mac, and got passed the inital part on windows. broke on the optimization runner, but im sure its to do with gcc on my machine, so thanks :)

**Comment by Tdarnell** [comment]
The data_fetcher now works fine, but I am getting sqlite errors like #249 where I wasn't getting them previously during the prediction phase. 

Did any requirements change between versions? I am going to attempt a pip re-install (using base python3 interpreter still from Ubuntu WSL, not conda)

**Comment by jack89roberts** [comment]
Hmm weird. Just checked and jupyter and seaborn are added to requirements on the develop branch. You could try removing those from `requirements.txt`, reinstalling in the environment as above, and see if that changes anything? More likely is that a version of something has changed (as we don't have package versions fixed in the dependencies at the moment).

**Comment by jack89roberts** [comment]
> thanks @jack89roberts ran perfectly on my mac, and got passed the inital part on windows. broke on the optimization runner, but im sure its to do with gcc on my machine, so thanks :)

@carlmacdiarmada - we haven't actually managed to get it working on Windows properly yet. In the readme there's a link to windows subsystem for Linux, which you could try as a workaround (basically run it on Linux from your Windows machine).

**Comment by Tdarnell** [comment]
A fresh install has solved the sqlite issue, this is now working as expected for me.
