### ISSUE TITLE
GW2+ Prediction

### ISSUE THREAD

**Issue by alexanderfolstad** [alan-turing-institute/AIrsenal#401]
Just ran optimization after GW1 end, and it suggests two transfers - while only having 1 free transfer. Is this a bug, or is it probable that it wants me to spend points to do the second trade?

airsenal_run_prediction --weeks_ahead 3
airsenal_run_optimization --weeks_ahead 3

**Comment by nbarlowATI** [comment]
Hi @alexanderfolstad, it  is hopefully taking the 4-point hit into account when making the transfer suggestions.  There is an option to `airsenal_run_optimization` to limit this - if you do
```
airsenal_run_optimization --weeks_ahead 3 --max_hit 0
```
it will hopefully give you the suggestions with no points hits (and if everything is working correctly, the total predicted score will be less than the one where it does advocate a points hit).

(Note that there are a few other options for the optimization, that can be seen with `airsenal_run_optimization --help` )

**Comment by mildfuzz** [comment]
I assume that the algorithm has decided a player is worth so much that taking a hit to free up finances is worth it

**Comment by mildfuzz** [comment]
Hmmm, so I ran the following:

```docker run -it --rm -v airsenal_data:/tmp/ -e "FPL_TEAM_ID=<My_Team_Id>" -e "FPL_PASSWORD=<My_Pass>" -e "FPL_LOGIN=<My_Login>" airsenal airsenal_run_optimization --weeks_ahead 3 --max_hit 0```

But it still recommends taking a point hit in GW2

**Comment by nbarlowATI** [comment]
Hi @mildfuzz ah, thanks - this looks like a bug then - I will look into it!

**Comment by nbarlowATI** [comment]
So, I think the problem here is that gameweeks 1-2 are a bit of a special case.   The function `get_free_transfers` in `airsenal/framework/utils.py` looks at how many transfers were done in the previous gameweeks, and in this case, correctly says that 0 transfers were done.   So it then (incorrectly) thinks we must have 2 free transfers this week.

Possible fixes/workarounds:
* People can run optimization with the `--num_free_transfers 1` argument to enforce this by hand
* We can modify `get_free_transfers` to deal with the special case of gameweek 1-2 (but not sure what happens if people join with new teams after gameweek 1- probably this would break for them)
* We can use the "current_picks" from the API, rather than relying on previous weeks' transfers.   This will directly get the number of free transfers, but does require the user to be logged in, which the current code doesn't.

**Comment by jack89roberts** [comment]
We'll also need to rewrite that function to not need the API for replay season functionality at some point, maybe by referring back to the earliest gameweek in the Transaction table (which should deal with teams starting after GW1). There's probably a few places now where we'd like the option of querying the current picks in the API if running on the next gameweek, but falling back to the database otherwise or if we don't have login details.

P.S. Looking at the current code I'm not convinced it would do the right thing if someone made more than 2 transfers in a week.

**Comment by mildfuzz** [comment]
Wish I'd known about these workarounds before making the transfers. Must remember to not blindly trust technology

**Comment by jack89roberts** [comment]
This should be fixed on our develop branch now. To install the version with the fix you can do the following from the parent `AIrsenal` directory:

```
git pull
git checkout develop
pip install .
```

**Comment by alexanderfolstad** [comment]
Running from the develop branch, max_hit still does not work. Neither does --num_free_transfers 1

**Comment by jack89roberts** [comment]
Sorry to hear that  @alexanderfolstad . Could you see how many strategies AIrsenal is optimising by running the following commands:

- `airsenal_run_optimization`: should be 21 strategies
- `airsenal_run_optimization --num_free_transfers 2`: should be 14 strategies
- `airsenal_run_optimization --max_hit 0`: should be 9 strategies

You can get the number of strategies from the "Total Progress" bar:

```
Total progress:   5%|██▎                                             | 1/21 [00:01<00:24,  1.25s/it]
```

In this case 21 strategies are being optimised (1/21  near the end). As soon as you see the number you can stop the optmisation running, you don't need to let it finish.

If the numbers don't match you could try pulling the repo again and re-installing with `pip install --force-reinstall .` to double-check you still don't have an old version running.

If it's still not working, could you let me know your team ID and the number of strategies returned by the commands above? Then I can try to check  what's going on later today.

**Comment by alexanderfolstad** [comment]
Hi,

Thanks for the quick reply.

I tried running the optimization again, both from my current install and also from the force restall. Both yielded the same amount of strategies:
airsenal_run_optimization: 14
airsenal_run_optimization --num_free_transfers 2: 14
airsenal_run_optimization --max_hit 0: 9

My team id is: 4124132

**Comment by nbarlowATI** [comment]
Hi @alexanderfolstad , just to check - when you ran `airsenal_run_optimization',  were you asked whether you would like to login to the FPL API?
If not, that means that for some reason it's not running the latest `develop` code.

If you were asked this, did you say yes, and did it seem to correctly log you in?   If you're not logged in, it won't be able to get your number of free transfers from the API, and will try and work it out from previous week's transfers instead (which will be wrong for this week).

**Comment by alexanderfolstad** [comment]
@nbarlowATI No, actually, I did not get asked that. That might be the explanation, then. I will try and reinstall the whole environment from scratch.

**Comment by jack89roberts** [comment]
I actually get an error when running with your ID:
```
❯ airsenal_run_optimization --fpl_team_id 4124132
Logged in successfully
Running optimization with fpl_team_id 4124132
Unable to access FPL API
Traceback (most recent call last):
  File "/Users/jroberts/opt/anaconda3/envs/arsnext/bin/airsenal_run_optimization", line 33, in <module>
    sys.exit(load_entry_point('airsenal', 'console_scripts', 'airsenal_run_optimization')())
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/scripts/fill_transfersuggestion_table.py", line 691, in main
    profile,
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/scripts/fill_transfersuggestion_table.py", line 385, in run_optimization
    fpl_team_id, gameweeks[0], apifetcher=fetcher
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/framework/utils.py", line 270, in get_free_transfers
    return apifetcher.get_num_free_transfers(fpl_team_id)
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/framework/data_fetcher.py", line 183, in get_num_free_transfers
    return squad_data["transfers"]["limit"]
TypeError: 'NoneType' object is not subscriptable
```

This looks similar to what's been picked up in #410 and #411

**Comment by jack89roberts** [comment]
Ignore me, that will be because I don't have the login details for your team.
