### ISSUE TITLE
run_optimization not working

### ISSUE THREAD

**Issue by tevans891** [alan-turing-institute/AIrsenal#694]
![image](https://github.com/user-attachments/assets/484caa80-077d-475d-ad22-eed5069dd44c)

I have attached a screenshot. whenever I try & run optimization it seems like it's working initially & then it flashes & changes to what the screenshot shows - have left it overnight & it just stays the same & gives me no other output.

I have tried uninstalling WSL & starting again from scratch & I get the same issue. 

I've been using it since the beginning of the season & It's been working great up until last week.

Any advice appreciated

**Comment by jack89roberts** [comment]
Hi @tevans891 , could you try pulling and reinstalling the latest version of AIrsenal (if you haven't already)? There were a few bugs associated with the changes to free transfers in FPL this season which could cause this, but we fixed those about a month ago (we hope!) The latest version is 1.9.0, which you can check by

```python
import airsenal
airsenal.__version__
```

in a Python shell.

**Comment by tevans891** [comment]
Never mind I have ran it again, I still get the squad is incomplete error at the bottom but I am getting xfer suggestion output for each week before that

====================================

Strategy for Team ID: 6209328
Baseline score: 166.98059917026094
Best score: 182.63561087184482
 ===============================================
 ========= Optimum strategy ====================
 ===============================================

 =========== Gameweek 9 ================

Chips played:  None

Players in:                     Players out:
-----------                     ------------
Alejandro Garnacho                      Mohamed Salah
Erling Haaland                  Alexander Isak

 =========== Gameweek 10 ================

Chips played:  None

Players in:                     Players out:
-----------                     ------------
Jamie Vardy                     Rodrigo Muniz Carvalho

 =========== Gameweek 11 ================

Chips played:  None

Players in:                     Players out:
-----------                     ------------
Marcus Rashford                 Bernardo Veiga de Carvalho e Silva

==========================
 Total score: 182

Getting starting squad for 6209328
Traceback (most recent call last):
  File "/home/tom/miniconda3/envs/airsenalenv/bin/airsenal_run_optimization", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/tom/miniconda3/envs/airsenalenv/lib/python3.12/site-packages/airsenal/scripts/fill_transfersuggestion_table.py", line 839, in main
    run_optimization(
  File "/home/tom/miniconda3/envs/airsenalenv/lib/python3.12/site-packages/airsenal/scripts/fill_transfersuggestion_table.py", line 607, in run_optimization
    best_squad = print_team_for_next_gw(
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/miniconda3/envs/airsenalenv/lib/python3.12/site-packages/airsenal/scripts/fill_transfersuggestion_table.py", line 397, in print_team_for_next_gw
    t.get_expected_points(next_gw, tag)
  File "/home/tom/miniconda3/envs/airsenalenv/lib/python3.12/site-packages/airsenal/framework/squad.py", line 398, in get_expected_points
    self.optimize_lineup(gameweek, tag)
  File "/home/tom/miniconda3/envs/airsenalenv/lib/python3.12/site-packages/airsenal/framework/squad.py", line 385, in optimize_lineup
    raise RuntimeError("Squad is incomplete")
RuntimeError: Squad is incomplete

**Comment by jack89roberts** [comment]
The squad is incomplete error shouldn't be happening either, `airsenal_run_pipeline --clean` might help possibly (that will delete and re-create the whole database), or it might be more likely to happen if you've already made transfers this week and/or your login/password are not set.

**Comment by tevans891** [comment]
Okay so I have not yet made any transfers this GW & I have 3 free available as I have not done anything with my team since GW4.

I believe the login credentials are fine as I get the login successful on 2nd attempt as normal. 

I have tried to run  `airsenal_run_pipeline --clean` but I get the following error doing that;

`/home/tom/miniconda3/envs/airsenalenv/lib/python3.12/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()`


The process then hangs and goes no further

**Comment by jack89roberts** [comment]
Ah ok, usually we get lucky and things work despite that warning, but this is a long-standing issue we need to find time to look at and fix properly. Going back to your other problem - if I run it with your team ID I get the same suggested transfers as you but not the squad is incomplete error at the end. My guess would still be that something might have gone wrong with your database. If the pipeline script doesn't work for you but the individual commands do you could try:

```
airsenal_setup_initial_db --clean
airsenal_update_db
airsenal_run_prediction
airsenal_run_optimization
```

which would have the same effect as `airsenal_run_pipeline --clean`.

**Comment by tevans891** [comment]
Thanks for all your help it's working fine again 😃
